config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :sanctuaries, :except => [:edit]
  root :to => 'sanctuaries#index'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates :time, :presence => :true
  validates_uniqueness_of :time

  has_and_belongs_to_many :sanctuaries
end

app/models/sanctuary.rb
class Sanctuary < ActiveRecord::Base
  validates :name, :presence => true
  validates_uniqueness_of :address

  has_and_belongs_to_many :appointments
end

app/models/session.rb
class Session < ActiveRecord::Base
  validates :time, :presence => :true
  validates_uniqueness_of :time

  has_and_belongs_to_many :sanctuaries
end

app/models/user.rb
class User <ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authorize
    redirect_to login_url, alert: "NOT AUTHORIZED. Must be logged in to do that." if current_user.nil?
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sanctuaries_controller.rb
class SanctuariesController < ApplicationController
  def index
    @sanctuaries = Sanctuary.all
  end

  def show
    @sanctuary = Sanctuary.find(params[:id])
  end

  def new
    @sanctuary = Sanctuary.new
  end

  def create
    @sanctuary = Sanctuary.create(sanctuary_params)
    if @sanctuary.save
      redirect_to sanctuaries_path, notice: "Your Sanctuary has been created!"
    else
      render 'new'
    end
  end

  def update
    @sanctuary = Sanctuary.find(params[:id])
    if @sanctuary.update(sanctuary_params)
      redirect_to sanctuary_path(@sanctuary), notice: "Your Sanctuary has been updated!"
    else
      render 'show'
    end
  end

  def destroy
    @sanctuary = Sanctuary.find(params[:id])
    @sanctuary.delete
    redirect_to sanctuaries_path, notice: "#{@sanctuary.name} has been deleted!"
  end

  private

  def sanctuary_params
    params.require(:sanctuary).permit(:id, :name, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "LOGGED OUT!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:new, :create]


  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h4>Please fix these errors:</h4>

  <% object.errors.full_messages.each do |message| %>
    <p class="bg-danger"><%= message %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div id="user_header", class="text-right">
      <% if current_user %>
        Logged in as <strong><%= current_user.username %></strong>
        <%= link_to "Log Out", logout_path %> or
        <%= link_to "Sign Up a New User", new_user_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>
    </div>

    <h1>Sanctuary Time Finder</h1>
    <p class="bg-primary"><%= flash[:notice] %></p>
    <p class="bg-danger"><%= flash[:alert] %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/sanctuaries/_form.html.erb
<%= render("layouts/errors", :object => @sanctuary) %>


<%= form_for(@sanctuary) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <%= f.submit(:class => "btn btn-primary btn-sm") %>
<% end %>

app/views/sanctuaries/index.html.erb
<% content_for(:title, "All Sanctuaries | Sanctuary Times Finder") %>


<h3>Sanctuaries</h3>
<div class="list-group">
  <% @sanctuaries.each do |sanctuary| %>
    <%= link_to sanctuary.name, sanctuary_path(sanctuary), :class => "list-group-item"%>
  <% end %>
</div>

<%= link_to "New Sanctuary", new_sanctuary_path, :class => "btn btn-primary" %>

app/views/sanctuaries/new.html.erb
<% content_for(:title, "Create New Sanctuary | Sanctuary Times Finder") %>


<h1>Create a new Sanctuary</h1>

<%= render 'form' %>

<%= link_to "Return to Sanctuary Index", sanctuaries_path %>

app/views/sanctuaries/show.html.erb
<% content_for(:title, "Sanctuary Info | Sanctuary Times Finder") %>


<h2> <p class="text-info"><%= @sanctuary.name %> </p></h2>
<h4> <%= @sanctuary.address %></h4>

<br />
<br />

<p><%= link_to "Return to Sanctuary Index", sanctuaries_path %></p>

<br />
<br />


<h4>Edit <%= @sanctuary.name %>:</h4>
<%= render 'form' %>
<br />
<p><%= link_to "Delete #{@sanctuary.name}", sanctuary_path(@sanctuary),
  :data => {:confirm => "You sure?",
            :method => "delete"},
  :class => "btn btn-danger btn-xs" %></p>

app/views/users/new.html.erb
<h1>Sign Up!</h1>


<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %><br />
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %><br />
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>